### ISSUE TITLE
Controller: Fix /form page being accessible while being logged out

### ISSUE THREAD

**Issue by kevinvongmany** [kevinvongmany/cinejournal-webapp#58]
Update `controllers/homeRoutes.js` so the form page requires authentication to access (use the `withAuth` middleware function so users are redirected to login).

**Comment by Lijujujune** [comment]
Hi Kevin, I was having an issue with logging out.
It's not logging me out unless I clear my cache/history from my browser.
I've:
1. Added in a logout route function in homeRoutes
2. Added withAuth to form route.
3. Added withAuth to watchlist route, otherwise the watchlist page will not be redirect to login page, even you can't see any movie list but it looks odd.
<img width="1372" alt="Screenshot 2024-09-13 at 3 23 34 PM" src="https://github.com/user-attachments/assets/e6ade930-1608-4e0d-bbb2-a0733bc2ba66">

4. fix a typo on watchlist handlebars
I've tested my code multiple times, but pls also test for me before merge these changes.
Thanks.

**Comment by kevinvongmany** [comment]
I think we should get rid of the /watchlist route, since it's already being rendered in the homepage we should probably delete it or comment it out. 

Thanks for raising that logout issue, I'll take a look and see why that's happening. We probably have to look at the /logout route in homeRoutes.js or public/js/logout.js

**Comment by Lijujujune** [comment]
not sure can we take it out, since the form page has a button link to the watchlist route.

**Comment by kevinvongmany** [comment]
Oh, you're right, well that's the bug, the form page needs to have that button linked to '/' instead of '/watchlist'.

**Comment by kevinvongmany** [comment]
@Lijujujune could you delete 'watchlist' from form.handlebars: line 8
![image](https://github.com/user-attachments/assets/79c1cbac-bdd1-46b0-87d2-e925609a8178)

And also delete homeRoutes.js: line #65-84 too?

![image](https://github.com/user-attachments/assets/3af952c7-3d9e-4ecd-8739-6a49e843fa6b)

Once done, commit and push your changes and let me know when you're done, we can merge those straight in.

**Comment by Lijujujune** [comment]
DONE!
